### ISSUE TITLE
UFC build

### ISSUE THREAD

**Issue by Kerube** [BlueFinBima/DCS-FA18C-UFC#3]
Hi
Same here, did no find a way to contact you. 
I have completed the electronics assembly of the board but have a few questions regarding the values of R9,7,5,10,11,12 I could not find the values anywhere so I placed 0 ohms resistors for the time being.
I have not powered the board yet, and I think I will have a few questions on the software loading. 
Hope to hear from you.

Regards

**Comment by psjshep** [comment]
I'd be very interested to know how you completed the electronics assembly in great detail....

Phil

**Comment by Kerube** [comment]
Hi Phil
I sent the boards to be built in China using the fabrication files provided.
I ordered the parts online from different vendors. Had a hard time finding the HOLTEK HT16K33 chip by itself, ended up buying the Adafuit board and removing the chip to use it on the UFC.
Purchased the Gateron switches and added the green LEDs, I recommend you try to find them with the LEDs, it will save you some time.
In overall assembling the board is easy. I am just waiting to find out the values of he resistors listed above, after that I will power it up and try to load the software. Hopefully it will work as planned.

**Comment by psjshep** [comment]
Thanks for that - appreciated

Phil

**Comment by psjshep** [comment]
To clarify in my mind, you are referring to Resistors R5,7,9,10,11 & 12 on the UFC board, not the DCS controller...

(I couldn't find their values in the CSV Bill of Materials file Hornet UFC 020a BOM.csv)

Phil

**Comment by Kerube** [comment]
Correct. I found some online schematics showing that those resistors range from 100 to 150 ohms and 10k for the encoder pull up. I will try those values this weekend and see how it goes.

If it does not work, I will have to wait until the OPENHORNET team finish their design and go from there.

**Comment by psjshep** [comment]
Good luck... keep us posted

Phil

**Comment by psjshep** [comment]
I'm not sure if this is the answer to your resistor query... but when I opened the files in the Eagle program for the UFC board...
- There's a "Manufacture" area on the RHS...
- "Cam..." button to launch CAM
- Assembly on LHS -> Pick & Place -> export file -> dump into some temporary directory on your desktop...

Inside the <dir>\CAMOutputs\assembly is a CSV file PnP_Hornet UFC 020a_back.csv


74HC138 | 107.01 | 134.24 | 90 | CD74HC238M | SOIC127P600X175-16N
-- | -- | -- | -- | -- | --
C10 | 14.58 | 13.61 | 270 | 100nF | C0805
C11 | 9.68 | 13.66 | 270 | 100nF | C0805
C12 | 165.56 | 13.94 | 270 | 100nF | C0805
C13 | 170.56 | 13.94 | 270 | 100nF | C0805
C2 | 170.71 | 119.63 | 270 | 100nF | C0805
C3 | 165.56 | 119.48 | 90 | 100nF | C0805
C5 | 165.35 | 65.67 | 90 | 100nF | C0805
C7 | 170.43 | 65.72 | 90 | 100nF | C0805
C8 | 9.55 | 65.77 | 90 | 100nF | C0805
C9 | 14.53 | 65.74 | 90 | 100nF | C0805
R10 | 170.01 | 27.81 | 270 |   | R0805
R11 | 166 | 27.83 | 270 |   | R0805
R12 | 164.01 | 27.82 | 270 |   | R0805
R14 | 167.96 | 27.77 | 90 | 10K | R0805
R2 | 11.87 | 28.02 | 90 | 10K | R0805
R49 | 38.83 | 43.66 | 180 | 39K | R1206
R5 | 7.87 | 28.09 | 270 |   | R0805
R50 | 38.83 | 67.03 | 180 | 39K | R1206
R51 | 60.93 | 43.91 | 180 | 39K | R1206
R52 | 60.93 | 65.76 | 180 | 39K | R1206
R53 | 83.28 | 43.66 | 180 | 39K | R1206
R54 | 6.57 | 123.67 | 180 | 39K | R1206
R55 | 38.83 | 87.86 | 180 | 39K | R1206
R56 | 36.29 | 108.1 | 180 | 39K | R1206
R57 | 60.93 | 109.95 | 180 | 39K | R1206
R58 | 61.18 | 88.36 | 180 | 39K | R1206
R59 | 47.27 | 95.32 | 0 | 39K | R1206
R60 | 33.61 | 95.93 | 270 | 39K | R1206
R7 | 9.84 | 28.02 | 270 |   | R0805
R9 | 13.97 | 28.09 | 270 |   | R0805
TP1 | 15.75 | 29.1 | 0 | PTR1TP13SQ | TP13SQ
TP2 | 6.12 | 29.03 | 0 | PTR1TP13SQ | TP13SQ
TP3 | 171.73 | 29.03 | 0 | PTR1TP13SQ | TP13SQ
TP4 | 162.31 | 29.1 | 0 | PTR1TP13SQ | TP13SQ
U$31 | 28.05 | 33.83 | 90 | Addr 0x71 | SOIC28
U$7 | 15.02 | 132.58 | 180 | PCF8575CTSSOP24 | TSSOP24


Could those be the values, bearing in mind I have no idea what I'm doing in that prog LOL ?

Phil

*Edit*
Looks like the 270 is some other column value....possibly the rotation degrees... the other rows with capacity & resistor values is blank for the ones you need... o well :(

**Comment by Kerube** [comment]
cool, the values are there, I don't get to see them when I open the excel file.
Nice

Thanks Phil 
God job.

**Comment by psjshep** [comment]
note the edit :(

**Comment by BlueFinBima** [comment]
Sorry for ignoring you (not deliberately).  Once I find my eagle VM, I'll take a look for values.  Failing that, I'll open up a UFC and take a look ;-)

**Comment by BlueFinBima** [comment]
OK, Resistors R5,7,9,10,11 & 12 are for the RGB LEDs if you're using them.  https://www.allaboutcircuits.com/tools/led-resistor-calculator/ .  I didn't use the RGB encoder in the end.  I'll add a PDF of the schematic to the repo.

**Comment by psjshep** [comment]
nice 1 - thank you....

Phil

**Comment by Kerube** [comment]
Ah, good. 
Thank you BlueFin.
I will finish assembling he controller board soon and then I should be able to load the software and start getting to work.

Regards

**Comment by BlueFinBima** [comment]
@Kerube Yes 10K on the encoder pull-ups.  Aliexpress provided my HT16K33's (slow and cheap) but my prototyping IC came from Adafruit, just like yours.  If you want to, let me know your email address, and I can invite you to a Slack channel if more communication is useful.

**Comment by Kerube** [comment]
thank you so much.
Here is my email
kerube23@gmail.com

**Comment by BlueFinBima** [comment]
Closing.. moved discussion to slack
